apiVersion: v1
kind: ServiceAccount
metadata:
  name: default
  namespace: default
  annotations:
     # Explicitly mapping the Kubernetes Service account to a Google Service Account.
     # TODO: Fix PROJECT_ID being hardcoded
     iam.gke.io/gcp-service-account: "sa-eth-priv-kunall@anthos-demo-kunall.iam.gserviceaccount.com"