apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ../bases

configMapGenerator:
  - name: geth-config
    literals:
      - networkid="420221216"
    files:
      - genesis.json
  - name: app-config
    literals:
      - cluster_name="dcentral-twitter-cluster"
      - cluster_project="kunal-scratch"
      - cluster_zone="us-central1-a"
      - cloud_sql_connection="kunal-scratch:us-central1:blockscout"
